### ISSUE TITLE
[QUESTION] : can we map dynamic keys

### ISSUE THREAD

**Issue by sgandon** [mitchellh/mapstructure#161]
Hello,
I have the following yaml struct
```yaml
environments: 
  missingFileHandler: error
  default: 
    values:
    - /foo/bar
  otherEnv:
    values:
    - /aaa/bbb
```
the missingFileHandler is optional and the *default*, *otherEnv* are dynamic (they are not known in advance).

Is there a way to use mapstructure to extract this using the following structs without specific unmarshall function ?
```golang
type Environments struct {
	MissingFileHandler string
	Envs               map[string]EnvSpecs
}
type EnvSpecs struct {
	Values []string
}
```
